### ISSUE TITLE
Package should expose 'normalise' as well

### ISSUE THREAD

**Issue by Arachnid** [flyswatter/eth-ens-namehash#1]
Or at least, it'd be really nice if it did that.

**Comment by flyswatter** [comment]
Oh, that's really reasonable. Now I feel silly for having exported a function instead of an object...  Dare I try something hacky like hanging a function on another function, to preserve backwards-compatibility?  Or maybe just a major version bump...

**Comment by Arachnid** [comment]
Personally, I think a major version bump would be fine at this point. If
you do that, I can dump a couple of deps from ethereum-ens and depend on
this instead. :)

**Comment by flyswatter** [comment]
Ok, doing that now.

**Comment by flyswatter** [comment]
Published to npm as `2.0.0`!

**Comment by Arachnid** [comment]
Thanks!
